### PR TITLE
save gcode for pcbs (srm20)

### PR DESCRIPTION
**Pull request by amandaghassaei**
Hi, this adds a few more settings to gcode export so that we can generate .nc files to load into the Roland SRM20's proprietary control software.  One day it might be nicer to include .nc export from the roland output panel, but this should work for now.
Thanks!
amanda

### CODE REVIEW

**Comment by fibasile** [comment]
Hi, what's wrong with the current roland mill srm20 process? It has save option too.

**Comment by amandaghassaei** [comment]
we were having trouble getting the rml files from the roland save into the new machine (srm20) - though we were able to communicate directly with the machine through the node server.  Gcode export for pcbs is also good for people not using non-roland machines that can read Gcode - like the Othermill, shopbot, and others.

**Comment by fibasile** [comment]
ok, thanks for helping!

**Comment by amandaghassaei** [comment]
thanks, how does master sync up to fabmodules.org?  I want to send this over to a new fab lab in Armenia.  Thanks!

**Comment by fibasile** [comment]
You are right I'm merging this to the public repo later today.

—
Fiore BasileMobile. +39 3284576081
Email. fiore.basile@gmail.com
Twitter. @fibasile

http://fablabcascina.org

http://fabconnections.org

http://fibasile.github.io
http://artigianatodigitale.com

**Comment by fibasile** [comment]
Merged into public repo.

**Pull request merged**
